### ISSUE TITLE
Ocaml bindings are broken

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-bindings#1]
- ocaml: SWIG is buggy. Please set in ocamldec.swg the following line:
  #define caml_array_length swig_caml_array_length
  test_wrap.cxx:855:54: error: declaration of C function 'int caml_array_length__(caml_value_t)' conflicts with
  In file included from /usr/lib64/ocaml/caml/alloc.h:22:0,
               from test_wrap.cxx:741:
  /usr/lib64/ocaml/caml/mlvalues.h:250:21: error: previous declaration 'mlsize_t caml_array_length__(caml_value_t)' here
  no

**Comment by radare** [comment]
Can we close this?

**Comment by radare** [comment]
ping @XVilka

**Comment by XVilka** [comment]
Another bug (OCaml 4.02.3, SWIG 3.0.8)
```
g++ -fPIC -shared r_bin_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/lib64/ocaml/ -Dcaml_array_length=caml_array_length__ -I/usr/include/libr -o r_bin.so -lr_io -lr_db -lr_util -lr_bin -L/usr/lib64/ocaml -lcamlrun
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/ocaml/libcamlrun.a(alloc.o): warning: relocation against `caml_alloc_dummy' in readonly section `.text'.
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/ocaml/libcamlrun.a(memory.o): relocation R_X86_64_PC32 against symbol `caml_stat_heap_size' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
... r_bin.so

....

swig -small -O -o r_asm_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/include/libr -c++ -c++ -ocaml r_asm.i
r_asm.i:18: Warning 314:  'type' is an ocaml keyword and it will be appropriately renamed
r_asm.i:71: Warning 314:  'to' is an ocaml keyword and it will be appropriately renamed
r_asm.i:131: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
r_asm.i:136: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
g++ -fPIC -shared r_asm_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/lib64/ocaml/ -Dcaml_array_length=caml_array_length__ -I/usr/include/libr -o r_asm.so -lr_syscall -lr_db -lr_parse -lr_util -lr_asm -L/usr/lib64/ocaml -lcamlrun
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/ocaml/libcamlrun.a(alloc.o): warning: relocation against `caml_alloc_dummy' in readonly section `.text'.
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/ocaml/libcamlrun.a(memory.o): relocation R_X86_64_PC32 against symbol `caml_stat_heap_size' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
... r_asm.so
```

**Comment by radare** [comment]
> On 31 May 2016, at 13:31, Anton Kochkov <notifications@github.com> wrote:
> 
> Another bug (OCaml 4.02.3, SWIG 3.0.8)
> 
> g++ -fPIC -shared r_bin_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/lib64/ocaml/ -Dcaml_array_length=caml_array_length__ -I/usr/include/libr -o r_bin.so -lr_io -lr_db -lr_util -lr_bin -L/usr/lib64/ocaml -lcamlrun
> /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/ocaml/libcamlrun.a(alloc.o): warning: relocation against `caml_alloc_dummy' in readonly section `.text'.
> /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/ocaml/libcamlrun.a(memory.o): relocation R_X86_64_PC32 against symbol `caml_stat_heap_size' can not be used when making a shared object; recompile with -fPIC
> /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> ... r_bin.so
> 
this is because you are linking 64bit r2 with 32bit ocaml

**Comment by XVilka** [comment]
Just checked and rebuilt it for 64bits - still the same.

**Comment by radare** [comment]
is ocaml built with -fPIC’ because the error says so

**Comment by XVilka** [comment]
Yes, you right, it missing `-fPIC`, like in this wiki https://wiki.gentoo.org/wiki/Project:AMD64/Fixing_-fPIC_Errors_Guide

**Comment by XVilka** [comment]
This is distro issue looks like. I'll try to figure out what's wrong.

**Comment by XVilka** [comment]
Still the same on a different distribution - Fedora:
```sh
$ valabind-cc --test ocaml
SWIG is buggy. Please set in ocamldec.swg the following line:                                                                                                                                                                                
#define caml_array_length swig_caml_array_length                                                                                                                                                                                             
/usr/bin/ld: /home/user/.opam/infer-4.02.3/lib/ocaml/libcamlrun.a(memory.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC                                           
/home/user/.opam/infer-4.02.3/lib/ocaml/libcamlrun.a: error adding symbols: Bad value                                                                                                                                                    
collect2: error: ld returned 1 exit status 
```

**Comment by radare** [comment]
Blame swig not me

**Comment by XVilka** [comment]
Found how to fix that in general - just choose needed version of ocaml, instead of using one from distributive:
```sh
opam switch create 4.04.1+fPIC
eval `opam env`
```
