### ISSUE TITLE
Arbitrary code exec

### ISSUE THREAD

**Issue by l4l** [radare/radare2-bindings#103]
[NodeJS Telegram Bot](https://github.com/radare/radare2-bindings/blob/master/r2pipe/nodejs/examples/tgbot/index.js) accept any comand besides determined in help. Is it ok?
I can type like "1000000pdf" and bad things can happen

**Comment by l4l** [comment]
Ok, sorry for dos-ing your bot. That was a test :(
Here's the fix

**Comment by radare** [comment]
It's on purpose. I have already filled an issue about this kind of hang and will push the fix soon

**Comment by l4l** [comment]
Well, I can't find the issue, where is it?
And should I close this issue/pull req?

**Comment by Maijin** [comment]
is fixed here https://github.com/radare/radare2/commit/23e7fbb398012ba1f21b40857f5db362a76c18a8
