### ISSUE TITLE
Invalid write of size 1   at 0x4E3C40B: r2p_write (r2pipe.c:206)

### ISSUE THREAD

**Issue by 0xspx** [radare/radare2-bindings#105]
Getting this from valgrind using the C pipe, which is using r_socket.h and r2pipe.c.
==31189== Invalid write of size 1
==31189==    at 0x4E3C40B: r2p_write (r2pipe.c:206)
==31189==    by 0x4E3C14B: r2p_cmd (r2pipe.c:159)

**Comment by radare** [comment]
This is not a bug in bindings. I just fixed it in r2 master
