### ISSUE TITLE
ImportError: No module named r_util

### ISSUE THREAD

**Issue by dhxkgozj** [radare/radare2-bindings#109]
root@ubuntu:~/radare2/radare2-bindings/python# python test-r2rc.py 
Traceback (most recent call last):
  File "test-r2rc.py", line 6, in <module>
    from r_util import *
ImportError: No module named r_util

Why is this a problem?

**Comment by radare** [comment]
You have to build the bindings first

**Comment by dhxkgozj** [comment]
radare build is completed but r_utils not found. 

 ./configure --prefix=/usr --enable-devel
$ cd python
$ PYTHON_CONFIG=python2.7-config make
$ su -
# PYTHON_CONFIG=python2.7-config make install


Another option is required?

**Comment by XVilka** [comment]
It means there was an error during the building - check your logs and paste
it here

**Comment by dhxkgozj** [comment]
reinstall sucess. Thank!
