### ISSUE TITLE
Separate all r2pipe from conventional bindings

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-bindings#114]
Right now it's all mixed here.
What I'm suggesting - move 'r2pipe' directory of this repo into the separate repository. Especially, since r2pipe is more actively developed.

**Comment by radare** [comment]
lgtm

**Comment by jvoisin** [comment]
And deprecate the bindings?

**Comment by XVilka** [comment]
Well, not sure about that, but some cleanup would be nice.

**Comment by radare** [comment]
nope, the bindings are nice. and will take more relevance after 1.0 when stabilizing the api.

**Comment by radare** [comment]
Done
