### ISSUE TITLE
r2pipe.py 0.8.4 broke support for non-r2lang methods and python3

### ISSUE THREAD

**Issue by dequis** [radare/radare2-bindings#119]
41d9662b221946399f8cad96b86c453aa2259929

That `print "RLANG IS SET"` is breaking python3.

Then there's this:

```python
		if in_rlang():
			print "RLANG IS SET"
			self._cmd = self._cmd_rlang
			return
		self._cmd = self._cmd_rlang
		return;
		# [dead code for other methods here]
```

If it's in rlang, use rlang. Otherwise, use rlang too, and break. Also, don't run the rest of the function. Ehhhhh.

Also, what is r2lang and how do I get it?

**Comment by radare** [comment]
r2pm -i lang-python

**Comment by dequis** [comment]
But the other ways to use the r2pipe module are still supported, right?

**Comment by XVilka** [comment]
Yes.

**Comment by radare** [comment]
Sure, thats just optional
