### ISSUE TITLE
recent radare2-bindings python build fail

### ISSUE THREAD

**Issue by kuh3h3** [radare/radare2-bindings#124]
` reandr  ~  radare2-bindings  git log
commit 92d4eb1115301416544d790af88fa4e6076bafd9
Author: pancake <pancake@nopcode.org>
Date:   Tue Jun 21 00:31:50 2016 +0200

    Add support for core plugins in python

 reandr  ~  radare2-bindings  ./configure --prefix=/usr --enable=python
==> Using valabind 0.10.0
==> Using swig 3.0.7
Checking valabind languages support...
 - python: yes
 - perl: yes
 - ruby: yes
 - lua: yes
 - go: no
 - java: yes
 - guile: yes
 - php5: yes
 - node-ffi: no
 - ctypes: yes
 - ocaml: no
 - cxx: yes (g++)
 - valac: yes
Supported langs:
 - python
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr'
checking for c compiler... gcc
checking for c++ compiler... g++
checking for valabind... /bin/valabind
checking for swig... /bin/swig
checking for g-ir-compiler... /bin/g-ir-compiler
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... yes
creating ./config.mk
creating r2pipe/vala/r2pipe.pc
cleaning temporally files... done

Final report:
 - PREFIX = /usr
 - HAVE_SWIG = 1
 - HAVE_VALABIND = 1
 - HAVE_GIRCOMPILER = 1

 reandr  ~  radare2-bindings  make
make -C libr/lang/p
make[1]: Entering directory '/home/reandr/radare2-bindings/libr/lang/p'
cc python.c -I/usr/include/libr  -Wall -DPREFIX=\"/usr\" -I. -Iduk -pthread -I/usr/include/lua-5.1 -I/usr/include/efl-1 -I/usr/include/elua-1 -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/efl-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/luajit-2.0  -I/usr/include/python2.7 -I/usr/include/python2.7  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -lpython2.7 -lpthread -ldl -lutil -lm -L/usr/lib  -lr_core -lr_util -shared \
  -lr_core -lr_util -shared -fPIC -o lang_python.so
/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/bin/ld: skipping incompatible /usr/lib/libutil.so when searching for -lutil
/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
cc -fPIC  -lr_core -lr_util -shared -o lang_csharp.so \
	-I/usr/include/libr -lr_util  csharp.c
cc -I/usr/include/libr  -Wall -DPREFIX=\"/usr\" -I. -Iduk -pthread -I/usr/include/lua-5.1 -I/usr/include/efl-1 -I/usr/include/elua-1 -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/efl-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/luajit-2.0    -c -o duktape.o duktape.c
cc -std=c99 -I/usr/include/libr  -Wall -DPREFIX=\"/usr\" -I. -Iduk -pthread -I/usr/include/lua-5.1 -I/usr/include/efl-1 -I/usr/include/elua-1 -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/efl-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina -I/usr/include/luajit-2.0  -fPIC  -lr_core -lr_util -shared \
	-o lang_duktape.so duktape.c
LANG lang_python.so  lang_csharp.so lang_duktape.so
make[1]: Leaving directory '/home/reandr/radare2-bindings/libr/lang/p'
make[1]: Entering directory '/home/reandr/radare2-bindings/python'
Build r_core -lr_core -lr_config -lr_cons -lr_io -lr_util -lr_flags -lr_asm -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_socket -lr_fs -lr_magic 
valabind-cc python r_core -NRadare -NSDB --swig -x --vapidir=../vapi ../vapi/r_core -I/usr/include/libr -lr_core -lr_config -lr_cons -lr_io -lr_util -lr_flags -lr_asm -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_socket -lr_fs -lr_magic
valabind --swig -I /usr/include/libr -x -N SDB -N Radare -x --vapidir ../vapi -o r_core.i -m r_core ../vapi/r_core --swig
NOTICE Symbol defined VALABIND_SWIG
NOTICE Adding dependency package glib-2.0
NOTICE Adding dependency package gobject-2.0
NOTICE Adding dependency package ../vapi/r_core
NOTICE Adding dependency package r_cmd
NOTICE Adding dependency package r_util
NOTICE Adding dependency package r_cons
NOTICE Adding dependency package r_anal
NOTICE Adding dependency package r_reg
NOTICE Adding dependency package r_hash
NOTICE Adding dependency package r_egg
NOTICE Adding dependency package r_asm
NOTICE Adding dependency package r_syscall
NOTICE Adding dependency package r_db
NOTICE Adding dependency package r_io
NOTICE Adding dependency package r_bp
NOTICE Adding dependency package r_debug
NOTICE Adding dependency package r_search
NOTICE Adding dependency package r_flags
NOTICE Adding dependency package r_config
NOTICE Adding dependency package r_bin
NOTICE Adding dependency package r_parse
NOTICE Adding dependency package r_lang
NOTICE Adding dependency package r_print
NOTICE Adding dependency package r_fs
NOTICE Adding dependency package r_magic
WARNING Method delete renamed to _delete (don't ask where)
WARNING Method continue renamed to cont (don't ask where)
swig -small -O -o r_core_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/include/libr -c++ -c++ -python r_core.i
r_core.i:40: Warning 302: Identifier 'RCoreAsmHitVector' redefined (ignored) (Renamed from 'vector< RCoreAsmHit >'),
r_core.i:39: Warning 302: previous definition of 'RCoreAsmHitVector' (Renamed from 'vector< RCoreAsmHit >').
r_core.i:42: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:41: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:46: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:41: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:47: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:41: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:62: Warning 302: Identifier 'charVector' redefined (ignored) (Renamed from 'vector< char >'),
r_core.i:58: Warning 302: previous definition of 'charVector' (Renamed from 'vector< char >').
r_core.i:63: Warning 302: Identifier 'charVector' redefined (ignored) (Renamed from 'vector< char >'),
r_core.i:58: Warning 302: previous definition of 'charVector' (Renamed from 'vector< char >').
r_core.i:92: Warning 314: 'print' is a python keyword, renaming to '_print'
r_core.i:324: Warning 314: 'from' is a python keyword, renaming to '_from'
r_core.i:329: Warning 314: 'from' is a python keyword, renaming to '_from'
r_core.i:586: Warning 314: 'import' is a python keyword, renaming to '_import'
r_core.i:1983: Warning 314: 'del' is a python keyword, renaming to '_del'
r_core.i:1654: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
r_core.i:1659: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
g++ -fPIC -shared r_core_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/include/python2.7 -I/usr/include/python2.7 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -I/usr/include/libr -o _r_core.so -lr_magic -lr_fs -lr_socket -lr_syscall -lr_search -lr_reg -lr_egg -lr_bp -lr_parse -lr_anal -lr_io -lr_lang -lr_bin -lr_hash -lr_debug -lr_asm -lr_flags -lr_util -lr_io -lr_cons -lr_config -lr_core -L/usr/local/lib -L/usr/pkg/lib -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
r_core_wrap.cxx: In function 'void delete_RListIter(RListIter*)':
r_core_wrap.cxx:7441:25: warning: statement has no effect [-Wunused-value]
   r_list_iter_free(self);
                         ^
r_core_wrap.cxx: In function 'bool RIO_plugin_open(RIO*, int, RIOPlugin*)':
r_core_wrap.cxx:8369:43: error: 'r_io_plugin_open' was not declared in this scope
   return r_io_plugin_open(self, fd, plugin);
                                           ^
r_core_wrap.cxx: In function 'bool RIO_plugin_close(RIO*, int, RIOPlugin*)':
r_core_wrap.cxx:8372:44: error: invalid conversion from 'int' to 'RIODesc* {aka r_io_desc_t*}' [-fpermissive]
   return r_io_plugin_close(self, fd, plugin);
                                            ^
r_core_wrap.cxx:8372:44: error: too many arguments to function 'int r_io_plugin_close(RIO*, RIODesc*)'
In file included from /usr/include/libr/r_fs.h:6:0,
                 from r_core_wrap.cxx:3251:
/usr/include/libr/r_io.h:332:11: note: declared here
 R_API int r_io_plugin_close(RIO *io, RIODesc *desc);
           ^
r_core_wrap.cxx: In function 'int RBreakpoint_recoil(RBreakpoint*, long long unsigned int)':
r_core_wrap.cxx:8477:32: error: 'r_bp_recoil' was not declared in this scope
   return r_bp_recoil(self, addr);
                                ^
r_core_wrap.cxx: In function 'int RDebug_trace_pc(RDebug*)':
r_core_wrap.cxx:8641:31: error: too few arguments to function 'int r_debug_trace_pc(RDebug*, long long unsigned int)'
   return r_debug_trace_pc(self);
                               ^
In file included from r_core_wrap.cxx:3254:0:
/usr/include/libr/r_debug.h:452:11: note: declared here
 R_API int r_debug_trace_pc(RDebug *dbg, ut64 pc);
           ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RAnalBlock_eflags_set(PyObject*, PyObject*)':
r_core_wrap.cxx:26912:71: error: 'RAnalBlock {aka struct r_anal_bb_t}' has no member named 'eflags'
     arg2 = static_cast< unsigned long long >(val2); if (arg1) (arg1)->eflags = arg2; resultobj = SWIG_Py_Void();
                                                                       ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RAnalBlock_eflags_get(PyObject*, PyObject*)':
r_core_wrap.cxx:26919:91: error: 'RAnalBlock {aka struct r_anal_bb_t}' has no member named 'eflags'
    arg1 = reinterpret_cast< RAnalBlock * >(argp1); result = (unsigned long long) ((arg1)->eflags);
                                                                                           ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RAnalOp_selector_set(PyObject*, PyObject*)':
r_core_wrap.cxx:27249:65: error: 'RAnalOp {aka struct r_anal_op_t}' has no member named 'selector'
     arg2 = static_cast< unsigned int >(val2); if (arg1) (arg1)->selector = arg2; resultobj = SWIG_Py_Void(); return resultobj;
                                                                 ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RAnalOp_selector_get(PyObject*, PyObject*)':
r_core_wrap.cxx:27256:82: error: 'RAnalOp {aka struct r_anal_op_t}' has no member named 'selector'
    arg1 = reinterpret_cast< RAnalOp * >(argp1); result = (unsigned int) ((arg1)->selector);
                                                                                  ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RRegItem_type_set(PyObject*, PyObject*)':
r_core_wrap.cxx:28659:60: error: invalid conversion from 'long int' to 'RRegisterType' [-fpermissive]
   arg2 = static_cast< long >(val2); if (arg1) (arg1)->type = arg2; resultobj = SWIG_Py_Void(); return resultobj; fail:
                                                            ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RDebug_newstate_set(PyObject*, PyObject*)':
r_core_wrap.cxx:31669:54: error: 'RDebug {aka struct r_debug_t}' has no member named 'newstate'
   arg2 = static_cast< int >(val2); if (arg1) (arg1)->newstate = arg2; resultobj = SWIG_Py_Void(); return resultobj; fail:
                                                      ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RDebug_newstate_get(PyObject*, PyObject*)':
r_core_wrap.cxx:31675:72: error: 'RDebug {aka struct r_debug_t}' has no member named 'newstate'
    arg1 = reinterpret_cast< RDebug * >(argp1); result = (int) ((arg1)->newstate);
                                                                        ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RDebugReason_type_set(PyObject*, PyObject*)':
r_core_wrap.cxx:32208:61: error: invalid conversion from 'int' to 'RDebugReasonType' [-fpermissive]
     arg2 = static_cast< int >(val2); if (arg1) (arg1)->type = arg2; resultobj = SWIG_Py_Void(); return resultobj; fail:
                                                             ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RDebugReason_bpi_set(PyObject*, PyObject*)':
r_core_wrap.cxx:32258:75: error: 'struct r_debug_reason_t' has no member named 'bpi'
    arg2 = reinterpret_cast< RBreakpointItem * >(argp2); if (arg1) (arg1)->bpi = arg2; resultobj = SWIG_Py_Void();
                                                                           ^
r_core_wrap.cxx: In function 'PyObject* _wrap_RDebugReason_bpi_get(PyObject*, PyObject*)':
r_core_wrap.cxx:32265:96: error: 'struct r_debug_reason_t' has no member named 'bpi'
    arg1 = reinterpret_cast< r_debug_reason_t * >(argp1); result = (RBreakpointItem *) ((arg1)->bpi);
                                                                                                ^
^C../rules.mk:34: recipe for target 'r_core.so' failed
make[1]: [r_core.so] 인터럽트 (ignored)
Makefile:46: recipe for target 'all' failed
make: *** [all] 인터럽트

 reandr  ~  r2 -V
0.10.3-288-gaaf3ff3  r2
0.10.3-288-gaaf3ff3  r_anal
0.10.3-288-gaaf3ff3  r_lib
0.10.3-288-gaaf3ff3  r_egg
0.10.3-288-gaaf3ff3  r_asm
0.10.3-288-gaaf3ff3  r_bin
0.10.3-288-gaaf3ff3  r_cons
0.10.3-288-gaaf3ff3  r_flags
0.10.3-288-gaaf3ff3  r_core
0.10.3-288-gaaf3ff3  r_crypto
0.10.3-288-gaaf3ff3  r_bp
0.10.3-288-gaaf3ff3  r_debug
0.10.3-288-gaaf3ff3  r_hash
0.10.3-288-gaaf3ff3  r_fs
0.10.3-288-gaaf3ff3  r_io
0.10.3-288-gaaf3ff3  r_magic
0.10.3-288-gaaf3ff3  r_parse
0.10.3-288-gaaf3ff3  r_reg
0.10.3-288-gaaf3ff3  r_sign
0.10.3-288-gaaf3ff3  r_search
0.10.3-288-gaaf3ff3  r_syscall
0.10.3-288-gaaf3ff3  r_util
 reandr  ~  r2 -v
radare2 0.10.4-git 11679 @ linux-x86-64 git.0.10.3-288-gaaf3ff3
commit: aaf3ff314c1b4ad77a6b71f31597010ebf14c104 build: 2016-06-22
`

**Comment by radare** [comment]
We are refactoring some apis in r2. This was asumed to be broken until the changes are done. If you want to fix it just updates the vapis and send a pr. Its easy

**Comment by radare** [comment]
Also looks like theres a miz of0.10.3 and 0.10.4, not sure if i bumped r2b version after release..

**Comment by radare** [comment]
fixed. see last commit to see how to fix thats stuff for the next time that it happens
