### ISSUE TITLE
How to DUMP the full hexa of each function extracted by analysis of binary file? 

### ISSUE THREAD

**Issue by hackmoonlight** [radare/radare2-bindings#130]
I used a script python from radare2-bindings to write a code analysing a binary file, i extracted the name , the start address and the size of each function , but i can't dump the hexa of each function , i am asking if there is a methode or python script in radare2 or another tool (capstone , miasm ...) to solve this problem .

```
 import sys
    import sqlite3 as lite
    try:
        import os, signal
        from r_core import *
    except:
        from r2.r_core import *

    rc = RCore()
    rc.file_open("/home/younes/Bureau/a.out", 0, 0)
    rc.bin_load("", 0)

    rc.anal_all()
    funcs = rc.anal.get_fcns()
    for f in funcs:
        blocks = f.get_bbs()
        print("+" + (72 * "-"))
        print("| FUNCTION: %s @ 0x%x" % (f.name, f.addr))
        print("| (%d blocks)" % (len (blocks)))
        print("+" + (72 * "-"))
        funcSize=0
        for b in blocks:
            end_byte = b.addr + b.size
            cur_byte = b.addr
            funcSize+=b.size

        print("   | f.size:      0x%x" %(funcSize))

    os.kill (os.getpid (), signal.SIGTERM) 
```

**Comment by Maijin** [comment]
1) Learn how to use the interweb
2) Learn how to python

```
import r2pipe
import sys

r2 = r2pipe.open(sys.argv[1])
r2.cmdj("aaa") # http://radare.today/posts/analysis-by-default/
function_list = r2.cmdj("aflj") # Analysis Function List Json

for function in function_list:
    var = r2.cmdj("p8j" + function["name"] + " @ " + function["name"]) # Print 8bit hexpair Json
```

There are probably even better way to do that using `@@@`

**Comment by hackmoonlight** [comment]
i want to print the full hexa of ech function

**Comment by Maijin** [comment]
. . .

**Comment by hackmoonlight** [comment]
what do you think about this code ? 
```
def analyze_opcode(addr=None):
	
		if addr == None:
			return __str_to_hash(r.cmd("ao"))
		return __str_to_hash(r.cmd("ao @ 0x%x"%addr))
```

**Comment by Maijin** [comment]
If it fits your need please close the issue.

**Comment by Maijin** [comment]
You can use `r2.cmdj("aoj")` to get json.

**Comment by Maijin** [comment]
I just gave you the answer with r2pipe what do you need more ? Do you want me to show you how to copy/paste ?

**Comment by hackmoonlight** [comment]
it dosen't work , sorry

**Comment by Maijin** [comment]
It works here.

**Comment by Maijin** [comment]
You obviously need to do something with var after it has been assigned.

**Comment by Maijin** [comment]
Can you detail output, what doesn't work

**Comment by Maijin** [comment]
Small typo in the code `@ function["name"]`was OBVIOUSLY` @ function["size"]`

I changed it.

**Comment by hackmoonlight** [comment]
hello ,  is there a solution with r2pipe to extract function addrsses ?

**Comment by radare** [comment]
aflq

**Comment by Maijin** [comment]
same as previous use `r2.cmdj("aflj")` to get in json

**Comment by radare** [comment]
fcn_offsets = r2.cmd(“aflq”).split(‘ ‘)

this is much faster than the json option which shows much more info. if u just need the offsets go for aflq

**Comment by hackmoonlight** [comment]
thank you @Maijin @radare

**Comment by radare** [comment]
and yes.. we should have aflqj to avoid that split

**Comment by radare** [comment]
https://github.com/radare/radare2/issues/5389

if anyone feels brave

**Comment by hackmoonlight** [comment]
function_list = r2.cmdj("aflj")
for function in function_list:
     print("0x%x"%(function['offset']))

**Comment by radare** [comment]
yep this is another way. but its way slower than using aflq
