### ISSUE TITLE
Nodejs bindings should follow node callback conventions

### ISSUE THREAD

**Issue by dweinstein** [radare/radare2-bindings#132]
- return err for first argument of callbacks (https://www.joyent.com/node-js/production/design/errors)
- async functions should actually be async. see https://howtonode.org/understanding-process-next-tick

**Comment by jpenalbae** [comment]
About the err, this was proposed back in the day, but wasn't done to avoid breaking the compatibility with old scripts.

About the second issue (async functions should actually be async), feel free to send a PR.

**Comment by radare** [comment]
agree on that. we should fix this before 1.0 (5 weeks)
