### ISSUE TITLE
Python bindings are broken, undefined symbol in _r_core.so

### ISSUE THREAD

**Issue by SheliakLyr** [radare/radare2-bindings#134]
In Python repl:
```
>>> importlib.import_module('r2._r_core')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /usr/lib/python2.7/site-packages/r2/_r_core.so: undefined symbol: r_db_add_unique
```
I think it is caused by a recent change in radare2, see radare/radare2#5158 and radare/radare2@f96f00d62ddfcc8ace4540d82081bf5dd6b02cf4.

**Comment by radare** [comment]
cant reproduce, works fine for me

**Comment by SheliakLyr** [comment]
I removed radare2/radare2-bindings (version 0.10.4) and compiled newest version from git. It works! I've managed to track the exact commit that fixed it: 24dc5250a478dc76561e68f35dfa836709c77d2
So the problem is already solved in git and occurs for version 0.10.4 only. Perhaps that's why you could not reproduce it?

I'm using Arch Linux btw. Not sure if this issue will manifest itself on other systems.

**Comment by radare** [comment]
This happens if u use r2 from git but bindings from stable version. Both r2b and r2 must be in the same version.

In less than two weeks there will be a new release. So dont worry too much about backporting stuff

**Comment by wget** [comment]
@SheliakLyr I'm on ArchLinux too and I wonder how you have successfully built it. Either using radare2-bindings, radare2-bindings-git or even compiling manually (taking vala and valabuild from sources) does not work. I still have compilation issues (error in code due to radare API changes).

**Comment by radare** [comment]
It builds fine in my machines and in our farm (jenkins and such)

**Comment by SheliakLyr** [comment]
@wget Yes, it compiled successfully. I used radare2-git and radare2-bindings-git. I also tried instructions from radare2 repo (sys/install.sh and r2pm install python) - and it also worked.

I don't remember any problems with vala. Right now:
```
$ pacman -Qs vala
local/vala 0.32.1-1
local/valabind 0.10.0-2
```
