### ISSUE TITLE
Is there a OCaml example?

### ISSUE THREAD

**Issue by binoopang** [radare/radare2-bindings#139]
Hello! 

I've tried to build `radare2-bindings` with OCaml on my Ubuntu Machine by just followed the well explained [README.md](https://github.com/radare/radare2-bindings/blob/master/README.md).

My OCaml environment is following.

 - Compiler : OCaml 4.02.3+PIC (OCaml with PIC runtime libraries)
 - Path : /home/user/.opam/4.02.3+PIC/

Everything looks fine. I could successfully `make` radare2-binding and I got ocaml shared library by following command.

``` bash
$ ./configure --prefix=/home/user/.opam/4.02.3+PIC/lib --enable=ocaml
$ make
$ cd ocaml
$ ls
Makefile  r_asm.ml   r_asm.so        r_bin.i   r_bin.mli  r_bin_wrap.cxx  r_core.ml   r_core.so
r_asm.i   r_asm.mli  r_asm_wrap.cxx  r_bin.ml  r_bin.so   r_core.i        r_core.mli  r_core_wrap.cxx
```
After the `make`, I invoked `make install` to copy libraries into target directory. 

I expect that compiled shared library should copied in `OCAML PATH` but no shared library copied. 
And OCaml TOP-Level interpreter can not find R2pipe module. I guess no ocaml modules installed 
properly. 

``` bash
# open R2pipe;;
Error: Unbound module R2pipe
# #use "r2pipe";;
Cannot find file r2pipe.
```
So, I want to know how to use OCaml binding of `r2pipe` after the compilation. And Is there a 
related OCaml example that implemented on top of r2pipe?

**Comment by radare** [comment]
Bindings != r2pipe

The module name for the bindings is r_asm, r_core, ... Nobody implemented r2pipe for ocaml yet. Feel free to be the one and send a pullreq to the r2pipe/ocaml directory.

The bindings you have built are generated by valabind and swig, so thats completely automatic. There are no examples for ocaml bindings but you can take any of the other languages supported as a template and just translate the syntax to make ocaml happy

**Comment by binoopang** [comment]
Thanks @radare ! 

Yes, I misunderstood the radare2-bindings.
I will look inside another supported langauge :)
