### ISSUE TITLE
Error during building/installing python bindings: building r_core.so fails

### ISSUE THREAD

**Issue by dnivra** [radare/radare2-bindings#143]
I am trying to build the python bindings for radare2 and I get the following error.

```cpp
r_core_wrap.cxx: In function 'int RCore_visual_cmd(RCore*, int)':
r_core_wrap.cxx:7380:36: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
   return r_core_visual_cmd(self, ch);

In file included from r_core_wrap.cxx:3311:0:
/usr/include/libr/r_core.h:240:11: note:   initializing argument 2 of 'int r_core_visual_cmd(RCore*, const char*)'
 R_API int r_core_visual_cmd(RCore *core, const char *arg);
```

This error occurs when running `make` but `make` still exits with EXIT_SUCCESS and the problem doesn't show up until `make install` when target `install-python` fails.

Update: Added more messages part of the error. Missed adding these earlier.

**Comment by dnivra** [comment]
@radare Did you mean master of radare2-bindings or radare2? If radare2-bindings, were the changes pushed? If radare2, I could find a commit on radare2, which didn't fix this issue.

**Comment by radare** [comment]
i mixed some issues :D git pull, i released r2b-1.2.1 with that definition updated.

thx for reporting

**Comment by dnivra** [comment]
Ah okay :). Thanks for the extremely quick fix! Building succeeds and I was able to `import r2` from python REPL so the fix work.

**Comment by radare** [comment]
cool!
