### ISSUE TITLE
invalid signature for visual_cmd in r_core

### ISSUE THREAD

**Issue by qwattash** [radare/radare2-bindings#148]
While compiling the python bindings from the master branch I got the following error.
```
r_core.vapi:163.36-163.45: error: `visual_cmd' already contains a definition for `arg'
r_core.vapi:163.24-163.33: note: previous definition of `arg' was here
```

The signature for the method seems to be wrong, **r_core.h** declares it as:
`R_API int r_core_visual_cmd(RCore *core, const char *arg);`
while in **r_core.vapi** it is declared as:
`public int visual_cmd(string arg, string arg);`

I believe the argument was repeated by mistake, the problem seems to be introduced by f81db47b.
Changing back to the previous signature seems to solve the compile error.
`public int visual_cmd(string arg);`

**Comment by radare** [comment]
should be fixed in master you can send a PR next time which is faster than describing all that thing

**Comment by radare** [comment]
thanks

**Comment by blshkv** [comment]
Sounds like it is my issue #146  :-)
