### ISSUE TITLE
no member named 'namehash' in 'r_flag_item_t'

### ISSUE THREAD

**Issue by hksuki** [radare/radare2-bindings#150]
I installed the python bindings on my mac, and I found there are problems I can't get it:
`r_core_wrap.cxx:33136:71: error: no member named 'namehash' in 'r_flag_item_t'
    arg2 = static_cast< unsigned long long >(val2); if (arg1) (arg1)->namehash = arg2; resultobj = SWIG_Py_Void();
                                                              ~~~~~~  ^
r_core_wrap.cxx:33143:90: error: no member named 'namehash' in 'r_flag_item_t'
   arg1 = reinterpret_cast< RFlagItem * >(argp1); result = (unsigned long long) ((arg1)->namehash);`

what's wrong?

**Comment by radare** [comment]
The vapi as always. Just remove the namehash field from the vapi file. Wanna try to send a pr?

**Comment by hksuki** [comment]
Thank you, I have it done!

**Comment by Maijin** [comment]
Then send it !

**Comment by hksuki** [comment]
I have changed the file, is there anything wrong?

**Comment by Maijin** [comment]
Make a Pull Request on this repository so it's fixed for everyone 👍

**Comment by hksuki** [comment]
I'm sorry, this is my first time editing files on github.Now I have sent the pr.

**Comment by radare** [comment]
Thanks!
