### ISSUE TITLE
Get data dependency graph using radare2

### ISSUE THREAD

**Issue by roj4s** [radare/radare2-bindings#152]
I want to create a Data dependency graph which is a graph obtained from the control flow graph in which the nodes are instructions and are connected if the instruction in the node use or modify the same memory space, this graph is also known as Program Dependence Graph. If it's not implemented how can I use radare from my own code to get the Control Flow Graph with the instructions in the same format as Capstone. Thanks in advance.

**Comment by Maijin** [comment]
Why is this an issue in radare2-bindings ?

**Comment by Maijin** [comment]
```
import r2pipe

r2 = r2pipe.open("/bin/ls")
r2.cmd('aaa')
print(r2.cmdj("agj @ main"))  # CFG on main
r2.quit()
```
