### ISSUE TITLE
QA Notice: Files built without respecting CFLAGS have been detected

### ISSUE THREAD

**Issue by blshkv** [radare/radare2-bindings#154]
```
 *  Please include the following list of files in your report:
 * /usr/lib64/perl5/vendor_perl/5.22.3/x86_64-linux/r2/r_asm.so
 * /usr/lib64/perl5/vendor_perl/5.22.3/x86_64-linux/r2/r_bin.so
 * /usr/lib64/perl5/vendor_perl/5.22.3/x86_64-linux/r2/r_core.so
 * /usr/lib64/radare2/1.3.0/lang_csharp.so
 * /usr/lib64/python2.7/site-packages/r2/_r_core.so
 * /usr/lib64/python2.7/site-packages/r2/_r_bin.so
 * /usr/lib64/python2.7/site-packages/r2/_r_asm.so

```

**Comment by blshkv** [comment]
Here is how we fixed it in capstone:
https://github.com/aquynh/capstone/issues/57

**Comment by radare** [comment]
this seems like a problem in valabind, not the bindings

**Comment by blshkv** [comment]
can you fix either of them? I have tried to compile with the latest valabind v1.3.0 and facing the same issue.

**Comment by radare** [comment]
btw, those are c++ files, are you talking about CFLAGS or CXXFLAGS? or share a build log or the env vars you expect to be exposed to the compiler and dont happen?

**Comment by radare** [comment]
also, valabind trims out some cflags in purpose because python-config shows sometimes some cflags and ldflags that are just breaking the build

**Comment by radare** [comment]
(see my last commit in the valabind repo)

**Comment by blshkv** [comment]
well done, I have applied the patch and the warning is gone. Thanks!

**Comment by radare** [comment]
Cool that my blindfix solved the issue. Ill do a new release of valabind

Thanks
