### ISSUE TITLE
Kill unused languages

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-bindings#166]
We need to focus on better support of the most usable bindings, rather than have bunch of unmaintaned dead code, adding tests for them and better crossplatform support.

 - `cxx` - it can just use C API directly
 - `dlang` - nobody used dlang bindings from what I've seen in a years
 - `guile` - I don't remember someone used them
 - `java` - since there is `jna`
 - `lua` - nobody asked a thing about using Lua
 - `luvit` - same
 - `newlisp` - nobody used newlisp from what I've seen in a years
 - `php` - nobody uses it.

I have doubts also of Ruby and Perl, but they are wider used in RE world.
In the worst case, if someone will come complaining of one of the removed bindings - it's easy to bring the needed stuff back.

So, your thoughs? @radare @Maijin @alvarofe @jpenalbae @jroimartin @lowlyw

**Comment by Maijin** [comment]
Not sure what's the benefit to remove those from this repository ? 
But maybe move the most used one in a dedicated repository and leave this one for the not used one could make a little bit more sense, but still lot of work/discussion for few gain imho.

**Comment by XVilka** [comment]
@Maijin well, for example some of them are failing to be built: https://github.com/radare/radare2-bindings/issues/126

**Comment by Maijin** [comment]
this won't solve this issue I guess only moving and explicitly saying XXX doesn't build will.

**Comment by radare** [comment]
Why? Dont remove this is autogenerated from swig, and it costs us 0 effort. Imho rm this issue
