### ISSUE TITLE
Separate `libr/lang` plugins into another repository

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-bindings#186]
Technically those are not really related to these autogenerated bindings, can perfectly work with r2pipe, so I think it make sense to put them into the another repository. It will improve their visibility too - here they are "lost". @radare what do you think?

**Comment by radare** [comment]
Agree on that but they are here because its a pain to have more repositories than the ones we have already and deps are the same, originally r2pipe was living in here too.

Is there any willing to evolve the lang plugins?

**Comment by XVilka** [comment]
Yes, I slowly improve Python one, will probably check other languages too, for consistency.

**Comment by radare** [comment]
Agree on that. This will make it clear the difference.. but its a bit confusing because of the amount of bindings we have

**Comment by XVilka** [comment]
@radare so, can you please do the repo for this when you have time?

**Comment by radare** [comment]
radare2-bindings-lang?

Any better name?

**Comment by XVilka** [comment]
maybe 'lang-plugins'?

**Comment by radare** [comment]
Why not just put them in extras? I dont expect too much wok to be done in those plugins in the near future

**Comment by XVilka** [comment]
We can try to put it in the separate repo, I will add more documentation on how to implement/improve them too. If there won't be much dynamics - you can put in radare2-extras then.

**Comment by radare** [comment]
maybe radare2-langs is the best name for it, but we need to copy the configure-langs logic, and i dont see much traction on this to have enough reasons to maintain another repo, which implies making releases more complex. if you want to contribute i would suggest to do it in this repo.
