### ISSUE TITLE
Go bindings: swig must be passed `-intgosize` flag on x64 on swig 2.0.9 or greater

### ISSUE THREAD

**Issue by williballenthin** [radare/radare2-bindings#20]
This is a new-ish flag required on recent swig releases.

Reference: http://code.google.com/p/go/issues/detail?id=4756

**Comment by luav** [comment]
What is the sense for the users to pass each time **-intgosize \`getconf LONG_BIT\`** (or similar using `uname -m`)?
Is there any reason why SWIG does not do it automatically?

**Comment by radare** [comment]
dunno, swig is a complete mess, but this thing can be done in the valabind-cc script to avoid having to do that by hand
