### ISSUE TITLE
Error searching lua pkgconfig  in archlinux

### ISSUE THREAD

**Issue by AitorATuin** [radare/radare2-bindings#7]
Makefile on libr/lang/p uses this code to look for the .pc files for lua

LUAPKG=$(shell pkg-config --list-all|awk '/lua-/{print $$1;}')

in arch linux pc filenames don't have the '-'.

**Comment by radare** [comment]
ping

**Comment by AitorATuin** [comment]
sorry, i have been really busy i will check it.

**Comment by radare** [comment]
let me know

**Comment by AitorATuin** [comment]
```
==> Using swig 3.0.7
Checking valabind languages support...
 - python: yes
 - perl: yes
 - ruby: yes
 - lua: yes
```

Yes, seems to work nicely

**Comment by AitorATuin** [comment]
and of course, it detected lua5.2 and lua5.3

**Comment by radare** [comment]
Awesome!

**Comment by radare** [comment]
should be fixed now in master. closing
