### ISSUE TITLE
Makefile:156: recipe for target 'install-python' failed

### ISSUE THREAD

**Issue by 230v** [radare/radare2-bindings#71]
-> Extracting radare2-bindings-0.9.8.tar.xz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
==> Using valabind 0.9.0
==> Using swig 3.0.5
Checking valabind languages support...
 - python: yes
 - perl: yes
 - ruby: yes
 - lua: yes
 - go: SWIG -go: -intgosize option required but not specified
no
 - java: test_wrap.c:135:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
no
 - guile: yes
 - php5: test_wrap.c:706:18: fatal error: zend.h: No such file or directory
 #include "zend.h"
                  ^
compilation terminated.
no
 - node-ffi: no
 - ctypes: yes
 - ocaml: SWIG is buggy. Please set in ocamldec.swg the following line:
#define caml_array_length swig_caml_array_length
/usr/bin/valabind-cc: line 106: ocamlc: command not found
test_wrap.cxx:741:24: fatal error: caml/alloc.h: No such file or directory
 #include <caml/alloc.h>
                        ^
compilation terminated.
no
 - cxx: yes (g++)
 - valac: yes
Supported langs:
 - python
checking build system type... i686-unknown-linux-gnu
checking host system type... i686-unknown-linux-gnu
checking target system type... i686-unknown-linux-gnu
checking for working directories... current
using prefix '/usr'
checking for c compiler... gcc
checking for c++ compiler... g++
checking for valabind... /usr/bin/valabind
checking for swig... /usr/bin/swig
checking for g-ir-compiler... no
checking pkg-config flags for r_core... yes
creating ./config.mk
cleaning temporally files... done

...

==> Entering fakeroot environment...
==> Starting package()...
make -C libr/lang/p install
make[1]: Entering directory '/tmp/yaourt-tmp-user/aur-r2-bindings/src/radare2-bindings-0.9.8/libr/lang/p'
mkdir -p /tmp/yaourt-tmp-user/aur-r2-bindings/pkg/r2-bindings//usr/lib/radare2/0.9.9-git/
[ -n "`ls *.so`" ] && cp -f *.so /tmp/yaourt-tmp-user/aur-r2-bindings/pkg/r2-bindings//usr/lib/radare2/0.9.9-git/ || true
make[1]: Leaving directory '/tmp/yaourt-tmp-user/aur-r2-bindings/src/radare2-bindings-0.9.8/libr/lang/p'
test -f python/_r_core.so
Makefile:156: recipe for target 'install-python' failed
make: *** [install-python] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build r2-bindings.
==> Restart building r2-bindings ? [y/N]
==> ------------------------------------

**Comment by radare** [comment]
this is a bug in the pkg, not in r2 itself. also we’re about to release 0.9.9 soon(R), so this problem is probably outdated. the error shows that the native python-swig binding wasnt compiled. mainly because from the steps i read in this log it’s doing: ./configure ; make install, without any make in the python directory.

**Comment by 230v** [comment]
r2-bindings-git just create pkg, but he override 
error: failed to commit transaction (conflicting files)
radare2-bindings-git: /usr/lib/radare2/0.9.9-git/lang_duktape.so exists in filesystem
radare2-bindings-git: /usr/lib/radare2/0.9.9-git/lang_python.so exists in filesystem

**Comment by dorneanu** [comment]
I'm having the same problem...

**Comment by radare** [comment]
Can u describe your build environment/ steps/etc in more detail? Run: cd python; make and. Paste output, etc

**Comment by dorneanu** [comment]
I'm trying to compile it on Arch. 

Configure: http://dpaste.com/3S80T5X

Then `cd python` and then `make`:
http://dpaste.com/1586KJV

Then `cd ..` and `make install`:

```
/usr/bin/install -m 644 vapi/*.vapi vapi/*.deps /usr/local/share/vala/vapi
make -C libr/lang/p install
make[1]: Entering directory '/home/victor/tmp/radare2-bindings/libr/lang/p'
mkdir -p //usr/lib/radare2/0.10.0-git/
[ -n "`ls *.so`" ] && cp -f *.so //usr/lib/radare2/0.10.0-git/ || true
ls: cannot access *.so: No such file or directory
make[1]: Leaving directory '/home/victor/tmp/radare2-bindings/libr/lang/p'
test -f python/_r_core.so
Makefile:156: recipe for target 'install-python' failed
make: *** [install-python] Error 1
```
In `python` there is no `_r_core.so`.

**Comment by radare** [comment]
Run install from the python directory

**Comment by radare** [comment]
I pushed a makefile cleanup that maybe it will help on this

**Comment by dorneanu** [comment]
```
╭─victor@Delia ~/tmp/radare2-bindings/python ‹system› ‹master*› 
╰─➤  pwd                                                                                                                                                                                                                                   1 ↵
/home/victor/tmp/radare2-bindings/python
╭─victor@Delia ~/tmp/radare2-bindings/python ‹system› ‹master*› 
╰─➤  make install
cd .. ; make install-python
make[1]: Entering directory '/home/victor/tmp/radare2-bindings'
test -f python/_r_core.so
Makefile:156: recipe for target 'install-python' failed
make[1]: *** [install-python] Error 1
make[1]: Leaving directory '/home/victor/tmp/radare2-bindings'
../rules.mk:56: recipe for target 'install' failed
make: *** [install] Error 2
```

Obviously there is no `_r_core.so` file:
```
╭─victor@Delia ~/tmp/radare2-bindings/python ‹system› ‹master*› 
╰─➤  find . -name "*core*"                                                                                                                                                                                                                 1 ↵
./r_core_wrap.cxx
./r_core.py
./r_core.i
./test-r_core.py
```

**Comment by dorneanu** [comment]
Updating to the latest radare2 package solved the problem.
