### ISSUE TITLE
ruby bindings does not respect system libdir variable

### ISSUE THREAD

**Issue by blshkv** [radare/radare2-bindings#75]
Hi,

By default, ruby bindings are getting installed into /usr/lib instead of /usr/lib64 (64bit system)

```
/usr/lib64/python2.7/site-packages/r2/r_core.py
/usr/lib/ruby/1.9.1/r2/test-r_core.rb
```

I'm compiling the software in a strict environment and it prevents me from installing ruby bindings
For more details, see the following document: https://devmanual.gentoo.org/archs/amd64/

**Comment by radare** [comment]
I pushed a fix for that in git, let me know if it works for you. Thanks!

**Comment by radare** [comment]
see c11a5dd7d343b101c2cceab03c31f2f59adadf70

**Comment by blshkv** [comment]
yes, fixed, thank you.
https://code.google.com/p/pentoo/source/detail?r=6611

**Comment by radare** [comment]
Cool! Thanks for reporting
