### ISSUE TITLE
build python bindings with error

### ISSUE THREAD

**Issue by reu-res** [radare/radare2-bindings#80]
`r_core_wrap.cxx:7227:62: error: too few arguments to function ‘RList* r_core_asm_strsearch(RCore*, const char*, long long unsigned int, long long unsigned int, int, int)’`

**Comment by radare** [comment]
Fixed. 7e95281dd8abd077c3245d87cd8a40ee6efbffad next time checkout the .h file and update the .vapi in a pullreq. Continuous integration is running again, so we should catch those kind of failed builds now.
