### ISSUE TITLE
`axtj` is broken in Python

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2-bindings#81]
Radare2 is not outputting JSON, but things like:
```
[{u'type': u'C', u'from': 4269326, u'opcode': u'call section..init'}]
```

Notice the `u` prefix; meaning that it's unicode.

**Comment by Maijin** [comment]
Works on py3

**Comment by radare** [comment]
this is what python generates after parsing the json. not my fault. axtj is fine imho

**Comment by radare** [comment]
pls paste code

**Comment by radare** [comment]
Can we close this issue?

**Comment by radare** [comment]
ping
