### ISSUE TITLE
Can't compile Python bindings

### ISSUE THREAD

**Issue by redfast00** [radare/radare2-bindings#87]
I followed the instructions at https://github.com/radare/radare2-bindings#python
These are my errors
http://pastebin.com/3xEjZCy5

**Comment by radare** [comment]
I guess u r using debian, and you didnt installed the vala-dev pkg. the basic vapi files for the vala compiler are not available acording to the error messages

**Comment by redfast00** [comment]
Thanks for the quick answer. I am indeed using a variant of debian (kali). I will check tomorrow if your solution works.

**Comment by redfast00** [comment]
So, I tried it again after "apt-get install vala*". Now I got another error. http://pastebin.com/rR0mNza1

**Comment by radare** [comment]
You should build evetything from git. Releases are suposed to be used only by distributions. Do u hace r2 from git and r2b from release maybe?

**Comment by redfast00** [comment]
I tried to compile r2b from git, and I got the exact same error, so I tried the releases. I'm sorry I confused you.

**Comment by redfast00** [comment]
This is still an issue, but I removed radare.

**Comment by Maijin** [comment]
@redfast00 instead of the bindings you should definitely take a look at the r2pipe which is much easier to install + much easier to use => https://github.com/radare/radare2-bindings/tree/master/r2pipe/python#r2pipe-for-python

**Comment by redfast00** [comment]
But I want to install bokken. Will it work?

**Comment by Maijin** [comment]
Bokken uses indeed the bindings.

Did you tried with `r2pm -i bokken` ?

**Comment by redfast00** [comment]
Now I did, but bokken complained about not having radare-bindings installed.

**Comment by Maijin** [comment]
`r2pm -i python` for the bindings?

**Comment by redfast00** [comment]
Oh ok, I'll check it out tomorrow. Thanks for helping me!

**Comment by redfast00** [comment]
r2pm gives the same error message :/

**Comment by radare** [comment]
Everything builds fine according to our continuous integration systems and all my local machines build fine too. So i guess the best way to help you would be to meet in IRC or just wait for the release and you’ll get packages and binary builds for everything. But if you want to use bokken you should stick to the last release. and there should be packages for all of them already. which distro do you use?

By the error you have provided

```
r_core_wrap.cxx: In function 'void RCore_anal_refs(RCore*, long long unsigned int, int)':
r_core_wrap.cxx:7137:34: error: invalid conversion from 'long long unsigned int' to 'const char*' [-fpermissive]
   r_core_anal_refs(self, addr, gv);
```
it says that the signature of this function is different, this happens when you have a different version of radare2 than the radare2-bindings installed. how have you installed r2? i would recommend you to completely remove r2 of your distro and then compile r2 using sys/install.sh, taking both projects from git as its explained in the website.

**Comment by redfast00** [comment]
Well, I did (FYI: my distro is Kali Linux: a debian based system).

**Comment by redfast00** [comment]
I'll ask it in irc

**Comment by radare** [comment]
This one comes with a very old version of radare

**Comment by redfast00** [comment]
But I compiled it from source (cloned the repo in /opt/radare2)

**Comment by radare** [comment]
Did you installed with sys/install.sh ? If not run make purge first

**Comment by Beuc** [comment]
Hi,

I run into the same issues and I think this is mostly a documentation issue. Can you make clearer that:

- valabind is quite close to radare (made by the same person) and isn't part of the mainstream vala stack. Meaning: make sure you have the very latest / Git version of "valabind"

- when compiling radare2 tag 0.9.9, the sys/python.sh script auto-downloads the latest *master* branch of radare2-python, which causes issues. Having the script grab a version compatible with radare2, or ask the user to do it, or simply warning about a version mismatch, can help a lot.

- last but not least, the radare2 homepage download page shows a large Linux penguin icon labelled "source", which I clicked on, and I though there was no release tarballs (just the Git repo). That made me miss the tarball links right below ;)

Cheers!

**Comment by radare** [comment]
Thanks for the tips. I'll take care of them to try to make things clear for new users
